#!/bin/sh -e

basedir=/usr/lib/jvm/{package_name}
files="jaotc jar jarsigner java javac javadoc javap jcmd jconsole jdb jdeprscan jdeps jhsdb jimage jinfo jjs jlink jmap jmod jps jrunscript jshell jstack jstat jstatd keytool pack200 rmic rmid rmiregistry serialver unpack200"

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
  for i in $files; do
    if [ -e $basedir/bin/$i ]; then
      path=$basedir/bin/$i
      if [ "$i" = "java" ]; then
          if [ -e $basedir/jre/bin/$i ]; then
              path=$basedir/jre/bin/$i
          fi
      fi
      update-alternatives --remove $i $path
    fi
  done
fi
