FROM ${BASE_IMAGE}
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y autoconf build-essential dialog file git java-common libasound2-dev libcups2-dev libfontconfig1-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libxt-dev libxtst-dev man unzip zip
RUN mkdir -p /usr/share/man/man1/
ARG JDK_PACKAGE
RUN addgroup --gid ${GROUP_ID} user
RUN useradd -l -m -u ${USER_ID} -g ${GROUP_ID} user
ADD $JDK_PACKAGE /
RUN dpkg -i /$JDK_PACKAGE
ADD run.sh /

